#!/bin/sh
# Copyright (C) 2025, Pasindu-Vishmika-Codimite.
# This program is free software; you can redistribute it and/or modify it under the terms of GPLv2

CUSTOM_PYTHON="/var/ossec/framework/python/bin/python3"

SCRIPT_PATH_NAME="$0"
DIR_NAME="$(cd "$(dirname "${SCRIPT_PATH_NAME}")"; pwd -P)"
SCRIPT_NAME="$(basename "${SCRIPT_PATH_NAME}")"
PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_NAME}.py"

# Run the integration script using custom Python interpreter
${CUSTOM_PYTHON} "${PYTHON_SCRIPT}" "$@"